### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by Kn99HN**
# Description
- Minor changes to project pages to space containers out.
- I like the text aligned center better : )
- About title is now centered like other pages. It's not bold yet like Project Title and Join Us Title since I don't know if that's intentional of you so I didn't change it

### CODE REVIEW

**Comment by NicholasLYang** [comment]
I have a few changes that I need to push up, so we're probably gonna have merge issues. I changed AboutPage and JoinUs to have white backgrounds as well

**Comment by Kn99HN** [comment]
You can copy some of minor changes to the code if you want. Otherwise, I can wait for your push

**Comment by NicholasLYang** [comment]
Alright I pushed. I'd recommend playing around with the new layout before making changes

**Comment by Kn99HN** [comment]
Awesome! I'll close this and open another PR later

**Pull request closed without merging**
